//! `$HOME/.config/hypr/monitors.conf`: the grammar and rule semantics shared
//! with the smplOS Lua loader, and the Settings writer.
//!
//! Grammar (hyprlang): `#` starts a comment anywhere and `##` is a literal
//! `#`. `monitor = <fields>` splits on commas; fields are trimmed. Forms:
//! * full `<sel>, <mode>, <position>, <scale>[, <key>, <value>]…` creates a
//!   fresh rule (transform 0, enabled), replacing any rule with the identical
//!   selector and moving it to the end. Options stop at the first empty key;
//!   integers are plain decimals and an invalid transform leaves 0;
//! * `<sel>, disable|disabled`: a fresh disabled rule, replaced the same way;
//! * `<sel>, transform, <n>`: copies the identical-selector rule with that
//!   transform to the end; a no-op without one;
//! * `<sel>, addreserved, <top>, <bottom>, <left>, <right>`: modifies the
//!   identical-selector rule in place, else appends a default rule.
//!
//! An output's effective rule is the last rule whose selector matches it
//! (`desc:` prefix or exact connector); the catch-all is ignored here.

use std::fs::{self, OpenOptions};
use std::io::{ErrorKind, Write};
use std::os::unix::fs::OpenOptionsExt;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use super::monitor::{Mode, Output};
use super::scale;

pub const HEADER: &str =
    "# Managed by smplOS Settings > Display. Lines for displays that are not connected are kept.";
const LEGACY_HEADERS: [&str; 1] =
    ["# Generated by settings -- edit freely, re-running settings will overwrite."];
/// Options carried from an output's previous rule onto the rewritten line.
const CARRIED_KEYS: [&str; 6] = [
    "vrr",
    "bitdepth",
    "cm",
    "sdrbrightness",
    "sdrsaturation",
    "icc",
];
const BACKUP_PREFIX: &str = "monitors.conf.bak-";
const BACKUPS_KEPT: usize = 5;

/// Removes a hyprlang comment; `##` is unescaped to a literal `#`.
pub fn strip_comment(line: &str) -> String {
    let mut content = String::with_capacity(line.len());
    let mut chars = line.chars().peekable();
    while let Some(c) = chars.next() {
        if c != '#' {
            content.push(c);
        } else if chars.peek() == Some(&'#') {
            chars.next();
            content.push('#');
        } else {
            break;
        }
    }
    content
}

fn escape(value: &str) -> String {
    value.replace('#', "##")
}

fn is_integer(text: &str) -> bool {
    let digits = text.strip_prefix('-').unwrap_or(text);
    !digits.is_empty() && digits.bytes().all(|b| b.is_ascii_digit())
}

fn parse_transform(text: &str) -> Option<i32> {
    if !is_integer(text) {
        return None;
    }
    text.parse().ok().filter(|t| (0..=7).contains(t))
}

#[derive(Debug, Clone, PartialEq)]
pub enum Form {
    Full {
        mode: String,
        position: String,
        scale: String,
        transform: i32,
        options: Vec<(String, String)>,
    },
    Disable,
    /// `None` when the value is not a valid transform (the line is ignored).
    Transform(Option<i32>),
    AddReserved(Vec<String>),
}

#[derive(Debug, Clone, PartialEq)]
pub struct MonitorLine {
    pub selector: String,
    pub form: Form,
}

/// Parses one line; `None` for anything that is not a `monitor` keyword.
pub fn parse_line(line: &str) -> Option<MonitorLine> {
    let content = strip_comment(line);
    let value = content
        .trim()
        .strip_prefix("monitor")?
        .trim_start()
        .strip_prefix('=')?;
    let fields: Vec<&str> = value.split(',').map(str::trim).collect();
    let field = |index: usize| fields.get(index).copied().unwrap_or("");
    let form = match field(1) {
        "disable" | "disabled" => Form::Disable,
        "transform" => Form::Transform(parse_transform(field(2))),
        "addreserved" => Form::AddReserved(fields.iter().skip(2).map(|f| f.to_string()).collect()),
        mode => {
            let mut transform = 0;
            let mut options = Vec::new();
            let mut index = 4;
            while index < fields.len() && !fields[index].is_empty() {
                let (key, value) = (fields[index], field(index + 1));
                if key == "transform" {
                    if let Some(valid) = parse_transform(value) {
                        transform = valid;
                    }
                } else {
                    options.push((key.to_string(), value.to_string()));
                }
                index += 2;
            }
            Form::Full {
                mode: mode.to_string(),
                position: field(2).to_string(),
                scale: field(3).to_string(),
                transform,
                options,
            }
        }
    };
    Some(MonitorLine {
        selector: field(0).to_string(),
        form,
    })
}

/// An explicit resolution, with a refresh rate when one was given.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct RuleMode {
    pub width: i32,
    pub height: i32,
    pub refresh: Option<f64>,
}

impl RuleMode {
    pub fn label(&self) -> String {
        match self.refresh {
            Some(refresh) => Mode {
                width: self.width,
                height: self.height,
                refresh,
            }
            .label(),
            None => format!("{}×{}", self.width, self.height),
        }
    }
}

fn leading_number(text: &str) -> Option<f64> {
    let end = text
        .char_indices()
        .find(|(_, c)| !(c.is_ascii_digit() || *c == '.'))
        .map_or(text.len(), |(i, _)| i);
    text[..end].parse().ok()
}

fn parse_rule_mode(text: &str) -> Option<RuleMode> {
    if ["pref", "highrr", "highres", "maxwidth", "modeline"]
        .iter()
        .any(|keyword| text.starts_with(keyword))
    {
        return None;
    }
    let (resolution, refresh) = match text.split_once('@') {
        Some((resolution, refresh)) => (resolution, Some(leading_number(refresh.trim())?)),
        None => (text, None),
    };
    let (width, height) = resolution.split_once('x')?;
    Some(RuleMode {
        width: width.trim().parse().ok()?,
        height: height.trim().parse().ok()?,
        refresh,
    })
}

fn parse_position(text: &str) -> Option<(i32, i32)> {
    if text.is_empty() || text.starts_with("auto") {
        return None;
    }
    let (x, y) = text.split_once('x')?;
    Some((x.trim().parse().ok()?, y.trim().parse().ok()?))
}

fn parse_scale(text: &str) -> Option<f64> {
    if text.is_empty() || text.starts_with("auto") {
        return None;
    }
    let value: f64 = text.parse().ok().filter(|v: &f64| v.is_finite())?;
    // Hyprland rejects scales below 0.25 and uses 1 instead.
    Some(if value < 0.25 { 1.0 } else { value })
}

/// One monitor rule after applying the file's lines in order.
#[derive(Debug, Clone, PartialEq)]
pub struct Rule {
    pub selector: String,
    pub disabled: bool,
    pub mode: Option<RuleMode>,
    pub position: Option<(i32, i32)>,
    pub scale: Option<f64>,
    pub transform: i32,
    pub options: Vec<(String, String)>,
}

impl Rule {
    fn fresh(selector: &str) -> Self {
        Self {
            selector: selector.to_string(),
            disabled: false,
            mode: None,
            position: None,
            scale: None,
            transform: 0,
            options: Vec::new(),
        }
    }
}

/// The rule list Hyprland builds from this file, in rule order.
pub fn rules(text: &str) -> Vec<Rule> {
    let mut rules: Vec<Rule> = Vec::new();
    for line in text.lines() {
        let Some(MonitorLine { selector, form }) = parse_line(line) else {
            continue;
        };
        match form {
            Form::Full {
                mode,
                position,
                scale,
                transform,
                options,
            } => {
                rules.retain(|rule| rule.selector != selector);
                rules.push(Rule {
                    mode: parse_rule_mode(&mode),
                    position: parse_position(&position),
                    scale: parse_scale(&scale),
                    transform,
                    options,
                    ..Rule::fresh(&selector)
                });
            }
            Form::Disable => {
                rules.retain(|rule| rule.selector != selector);
                rules.push(Rule {
                    disabled: true,
                    ..Rule::fresh(&selector)
                });
            }
            Form::Transform(Some(transform)) => {
                if let Some(index) = rules.iter().position(|rule| rule.selector == selector) {
                    let mut rule = rules.remove(index);
                    rule.transform = transform;
                    rules.push(rule);
                }
            }
            Form::Transform(None) => {}
            Form::AddReserved(_) => {
                if !rules.iter().any(|rule| rule.selector == selector) {
                    rules.push(Rule::fresh(&selector));
                }
            }
        }
    }
    rules
}

/// The last rule whose selector matches `output` (never the catch-all).
pub fn effective<'a>(rules: &'a [Rule], output: &Output) -> Option<&'a Rule> {
    rules
        .iter()
        .rev()
        .find(|rule| output.matches_selector(&rule.selector))
}

/// `desc:<description>` when it can only ever match this output, otherwise
/// the connector name. Descriptions survive connector renumbering (DP-3
/// becoming DP-4 after a re-plug), connector names do not.
pub fn choose_selector(output: &Output, outputs: &[Output]) -> String {
    let description = output.description.as_str();
    let usable = !description.is_empty()
        && description.trim() == description
        && !description
            .chars()
            .any(|c| c == '#' || c == ',' || c.is_control());
    if usable {
        let selector = format!("desc:{description}");
        if outputs
            .iter()
            .filter(|other| other.name != output.name)
            .all(|other| !other.matches_selector(&selector))
        {
            return selector;
        }
    }
    output.name.clone()
}

/// What Apply writes for one output.
#[derive(Debug, Clone, PartialEq)]
pub struct Target {
    pub name: String,
    pub mode: Mode,
    pub x: i32,
    pub y: i32,
    pub scale: f64,
    pub transform: i32,
}

/// A target with its chosen selector.
#[derive(Debug, Clone, PartialEq)]
pub struct Planned {
    pub selector: String,
    pub target: Target,
}

pub fn format_line(selector: &str, target: &Target, options: &[(String, String)]) -> String {
    let mut line = format!(
        "monitor = {selector}, {}, {}x{}, {}, transform, {}",
        target.mode.conf_text(),
        target.x,
        target.y,
        scale::format(target.scale),
        target.transform
    );
    for (key, value) in options {
        line.push_str(&format!(", {}, {}", escape(key), escape(value)));
    }
    line
}

fn valid_option(key: &str, value: &str) -> bool {
    match key {
        "vrr" => is_integer(value),
        "sdrbrightness" | "sdrsaturation" => value.parse::<f64>().is_ok_and(f64::is_finite),
        _ => !value.is_empty(),
    }
}

fn carried_options(rule: &Rule) -> Vec<(String, String)> {
    if rule.disabled {
        return Vec::new();
    }
    rule.options
        .iter()
        .filter(|(key, value)| CARRIED_KEYS.contains(&key.as_str()) && valid_option(key, value))
        .cloned()
        .collect()
}

fn is_header(line: &str) -> bool {
    let line = line.trim();
    line == HEADER || LEGACY_HEADERS.contains(&line)
}

fn split_lines(text: &str) -> Vec<&str> {
    let mut lines: Vec<&str> = text.split('\n').collect();
    if text.ends_with('\n') {
        lines.pop();
    }
    lines
}

/// Rewrites `existing` for the planned outputs.
///
/// Every line whose selector matches a written output is replaced; options
/// other than transform (vrr, bitdepth, cm, sdr*, icc) from that output's
/// effective rule move onto the new line, and its `addreserved` lines are
/// re-emitted after it. Everything else (comments, the catch-all, rules for
/// disconnected, disabled, virtual or mirroring outputs, unknown content) is
/// kept verbatim in order. A line that also matches a present output that is
/// not being written is kept too, so that output is never changed.
pub fn merge(existing: &str, planned: &[Planned], outputs: &[Output]) -> String {
    let rules = rules(existing);
    let is_planned = |output: &&Output| planned.iter().any(|p| p.target.name == output.name);
    let written: Vec<&Output> = outputs.iter().filter(is_planned).collect();
    let others: Vec<&Output> = outputs.iter().filter(|o| !is_planned(o)).collect();
    let mut kept: Vec<&str> = Vec::new();
    let mut reserved: Vec<(String, String)> = Vec::new();
    for line in split_lines(existing) {
        if is_header(line) {
            continue;
        }
        if let Some(parsed) = parse_line(line) {
            let hits: Vec<&&Output> = written
                .iter()
                .filter(|output| output.matches_selector(&parsed.selector))
                .collect();
            let shared = others
                .iter()
                .any(|output| output.matches_selector(&parsed.selector));
            if !hits.is_empty() && !shared {
                if let Form::AddReserved(values) = &parsed.form {
                    let values = values
                        .iter()
                        .map(|v| escape(v))
                        .collect::<Vec<_>>()
                        .join(", ");
                    for output in hits {
                        reserved.push((output.name.clone(), values.clone()));
                    }
                }
                continue;
            }
        }
        kept.push(line);
    }
    while kept.first().is_some_and(|line| line.trim().is_empty()) {
        kept.remove(0);
    }
    while kept.last().is_some_and(|line| line.trim().is_empty()) {
        kept.pop();
    }

    let mut ordered: Vec<&Planned> = planned.iter().collect();
    ordered.sort_by(|a, b| {
        (a.target.y, a.target.x, &a.target.name).cmp(&(b.target.y, b.target.x, &b.target.name))
    });
    let mut text = format!("{HEADER}\n");
    if !kept.is_empty() {
        text.push('\n');
        for line in kept {
            text.push_str(line);
            text.push('\n');
        }
    }
    if !ordered.is_empty() {
        text.push('\n');
    }
    for planned in ordered {
        let options = outputs
            .iter()
            .find(|output| output.name == planned.target.name)
            .and_then(|output| effective(&rules, output))
            .map(carried_options)
            .unwrap_or_default();
        text.push_str(&format_line(&planned.selector, &planned.target, &options));
        text.push('\n');
        // In-place modifications: the last of identical lines decides, so
        // keep the last occurrence of duplicates.
        let mut lines: Vec<&str> = Vec::new();
        for (name, values) in reserved.iter().rev() {
            if *name == planned.target.name && !lines.contains(&values.as_str()) {
                lines.push(values);
            }
        }
        for values in lines.into_iter().rev() {
            text.push_str(&format!(
                "monitor = {}, addreserved, {values}\n",
                planned.selector
            ));
        }
    }
    text
}

/// `monitors.conf` as Hyprland reads it (HOME-based, never XDG_CONFIG_HOME)
/// and, for a symlink, the file that is actually read and replaced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConfPath {
    pub link: PathBuf,
    pub target: PathBuf,
}

impl ConfPath {
    pub fn for_home(home: &Path) -> Result<Self, String> {
        let link = home.join(".config/hypr/monitors.conf");
        let target = match fs::symlink_metadata(&link) {
            Ok(meta) if meta.file_type().is_symlink() => {
                let target = fs::canonicalize(&link).map_err(|error| {
                    format!(
                        "{} is a symlink that can't be resolved: {error}",
                        link.display()
                    )
                })?;
                if !fs::metadata(&target).is_ok_and(|meta| meta.is_file()) {
                    return Err(format!(
                        "{} does not point to a regular file",
                        link.display()
                    ));
                }
                target
            }
            Ok(meta) if meta.is_file() => link.clone(),
            Ok(_) => return Err(format!("{} is not a regular file", link.display())),
            Err(error) if error.kind() == ErrorKind::NotFound => link.clone(),
            Err(error) => return Err(format!("can't inspect {}: {error}", link.display())),
        };
        Ok(Self { link, target })
    }

    /// The current content; `None` when the file does not exist.
    pub fn read(&self) -> Result<Option<String>, String> {
        match fs::read_to_string(&self.target) {
            Ok(text) => Ok(Some(text)),
            Err(error) if error.kind() == ErrorKind::NotFound => Ok(None),
            Err(error) => Err(format!("can't read {}: {error}", self.target.display())),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Written {
    /// The new content was byte-identical; nothing was touched.
    Unchanged,
    Replaced,
}

struct Temporary(PathBuf);

impl Drop for Temporary {
    fn drop(&mut self) {
        if let Err(error) = fs::remove_file(&self.0) {
            if error.kind() != ErrorKind::NotFound {
                eprintln!("[settings] cannot remove display temporary file: {error}");
            }
        }
    }
}

fn io_error(action: &str, path: &Path, error: std::io::Error) -> String {
    format!("can't {action} {}: {error}", path.display())
}

/// Copies the previous content to `monitors.conf.bak-YYYYmmdd-HHMMSS` next
/// to the path Hyprland reads (where the OS monitors-guard restores from).
fn backup(path: &ConfPath, previous: &str, stamp: &str) -> Result<PathBuf, String> {
    let directory = path.link.parent().ok_or("monitors.conf has no directory")?;
    let mut candidate = directory.join(format!("{BACKUP_PREFIX}{stamp}"));
    for attempt in 2..100 {
        match OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&candidate)
        {
            Ok(mut file) => {
                if let Ok(meta) = fs::metadata(&path.target) {
                    file.set_permissions(meta.permissions())
                        .map_err(|e| io_error("set permissions on", &candidate, e))?;
                }
                file.write_all(previous.as_bytes())
                    .and_then(|()| file.sync_all())
                    .map_err(|e| io_error("write", &candidate, e))?;
                return Ok(candidate);
            }
            Err(error) if error.kind() == ErrorKind::AlreadyExists => {
                candidate = directory.join(format!("{BACKUP_PREFIX}{stamp}-{attempt}"));
            }
            Err(error) => return Err(io_error("create", &candidate, error)),
        }
    }
    Err(format!("too many backups named {BACKUP_PREFIX}{stamp}"))
}

/// Sort key of a Settings backup name: (YYYYmmdd-HHMMSS, collision number).
fn backup_key(name: &str) -> Option<(String, u32)> {
    let rest = name.strip_prefix(BACKUP_PREFIX)?;
    let stamp = rest.get(..15)?;
    let bytes = stamp.as_bytes();
    let digits = |range: std::ops::Range<usize>| bytes[range].iter().all(u8::is_ascii_digit);
    if bytes[8] != b'-' || !digits(0..8) || !digits(9..15) {
        return None;
    }
    let number = match &rest[15..] {
        "" => 1,
        suffix => {
            let digits = suffix.strip_prefix('-')?;
            if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
                return None;
            }
            digits.parse().ok()?
        }
    };
    Some((stamp.to_string(), number))
}

/// Keeps only the newest Settings backups (other files are never touched).
/// The backup just written always survives, even if the clock went back.
fn prune_backups(directory: &Path, created: Option<&Path>) {
    let Ok(entries) = fs::read_dir(directory) else {
        return;
    };
    let mut backups: Vec<((String, u32), PathBuf)> = entries
        .flatten()
        .filter(|entry| Some(entry.path().as_path()) != created)
        .filter_map(|entry| {
            let key = backup_key(entry.file_name().to_str()?)?;
            entry
                .file_type()
                .ok()?
                .is_file()
                .then(|| (key, entry.path()))
        })
        .collect();
    backups.sort();
    let kept = BACKUPS_KEPT - usize::from(created.is_some());
    let excess = backups.len().saturating_sub(kept);
    for (_, path) in backups.into_iter().take(excess) {
        if let Err(error) = fs::remove_file(&path) {
            eprintln!("[settings] cannot prune {}: {error}", path.display());
        }
    }
}

/// Atomically replaces the file with `text` unless it is byte-identical:
/// back up the previous content, write a temporary file in the target's
/// directory with the same mode, fsync, check nobody changed the file in the
/// meantime, then rename over the target (a symlink stays a symlink).
pub fn replace(
    path: &ConfPath,
    previous: Option<&str>,
    text: &str,
    stamp: &str,
) -> Result<Written, String> {
    static NEXT: AtomicU64 = AtomicU64::new(0);
    if previous == Some(text) {
        return Ok(Written::Unchanged);
    }
    const CHANGED: &str = "monitors.conf changed while saving, so nothing was replaced";
    if path.read()?.as_deref() != previous {
        return Err(CHANGED.into());
    }
    let directory = path
        .target
        .parent()
        .ok_or("monitors.conf has no directory")?;
    fs::create_dir_all(directory).map_err(|e| io_error("create", directory, e))?;
    let created = match previous {
        Some(previous) => Some(backup(path, previous, stamp)?),
        None => None,
    };
    let temporary = Temporary(directory.join(format!(
        ".monitors.conf.{}.{}.tmp",
        std::process::id(),
        NEXT.fetch_add(1, Ordering::Relaxed)
    )));
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o644)
        .open(&temporary.0)
        .map_err(|e| io_error("create", &temporary.0, e))?;
    if previous.is_some() {
        let permissions = fs::metadata(&path.target)
            .map_err(|e| io_error("inspect", &path.target, e))?
            .permissions();
        file.set_permissions(permissions)
            .map_err(|e| io_error("set permissions on", &temporary.0, e))?;
    }
    file.write_all(text.as_bytes())
        .and_then(|()| file.sync_all())
        .map_err(|e| io_error("write", &temporary.0, e))?;
    drop(file);
    if path.read()?.as_deref() != previous {
        return Err(CHANGED.into());
    }
    fs::rename(&temporary.0, &path.target).map_err(|e| io_error("replace", &path.target, e))?;
    if let Ok(directory) = fs::File::open(directory) {
        if let Err(error) = directory.sync_all() {
            eprintln!("[settings] cannot sync display settings directory: {error}");
        }
    }
    if let Some(directory) = path.link.parent() {
        prune_backups(directory, created.as_deref());
    }
    Ok(Written::Replaced)
}

/// Local time as YYYYmmdd-HHMMSS for backup names.
pub fn local_stamp() -> String {
    // SAFETY: time/localtime_r only write the provided out-parameters.
    unsafe {
        let now = libc::time(std::ptr::null_mut());
        let mut tm: libc::tm = std::mem::zeroed();
        if libc::localtime_r(&now, &mut tm).is_null() && libc::gmtime_r(&now, &mut tm).is_null() {
            return "00000000-000000".into();
        }
        format!(
            "{:04}{:02}{:02}-{:02}{:02}{:02}",
            tm.tm_year + 1900,
            tm.tm_mon + 1,
            tm.tm_mday,
            tm.tm_hour,
            tm.tm_min,
            tm.tm_sec
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::display::monitor::tests::{live_pair, output_json, outputs};
    use std::os::unix::fs::{symlink, PermissionsExt};

    struct Fixture(PathBuf);

    impl Fixture {
        fn new() -> Self {
            static NEXT: AtomicU64 = AtomicU64::new(0);
            let path = std::env::temp_dir().join(format!(
                "settings-display-conf-test-{}-{}",
                std::process::id(),
                NEXT.fetch_add(1, Ordering::Relaxed)
            ));
            fs::create_dir_all(path.join(".config/hypr")).unwrap();
            Self(path)
        }

        fn hypr(&self) -> PathBuf {
            self.0.join(".config/hypr")
        }

        fn backups(&self) -> Vec<String> {
            let mut names: Vec<String> = fs::read_dir(self.hypr())
                .unwrap()
                .flatten()
                .map(|e| e.file_name().into_string().unwrap())
                .filter(|n| n.starts_with(BACKUP_PREFIX))
                .collect();
            names.sort();
            names
        }
    }

    impl Drop for Fixture {
        fn drop(&mut self) {
            fs::remove_dir_all(&self.0).unwrap();
        }
    }

    fn target(
        name: &str,
        mode: (i32, i32, f64),
        position: (i32, i32),
        scale: f64,
        transform: i32,
    ) -> Target {
        Target {
            name: name.into(),
            mode: Mode {
                width: mode.0,
                height: mode.1,
                refresh: mode.2,
            },
            x: position.0,
            y: position.1,
            scale,
            transform,
        }
    }

    fn plan(outputs: &[Output], targets: &[Target]) -> Vec<Planned> {
        targets
            .iter()
            .map(|t| Planned {
                selector: choose_selector(
                    outputs.iter().find(|o| o.name == t.name).unwrap(),
                    outputs,
                ),
                target: t.clone(),
            })
            .collect()
    }

    fn live_targets() -> Vec<Target> {
        vec![
            target("HDMI-A-1", (2560, 1440, 59.95), (0, 0), 1.0, 0),
            target("DP-3", (1920, 1080, 60.0), (2560, 0), 1.0, 1),
        ]
    }

    const LIVE_FILE: &str = "# Generated by settings -- edit freely, re-running settings will overwrite.\n\nmonitor = HDMI-A-1, 2560x1440@59.95, 0x0, 1.00, transform, 0\nmonitor = DP-3, 1920x1080@60.00, 2560x0, 1.00, transform, 1\n";

    #[test]
    fn comments_and_escaped_hashes_follow_hyprlang() {
        assert_eq!(
            strip_comment("monitor = DP-1, preferred # note"),
            "monitor = DP-1, preferred "
        );
        assert_eq!(
            strip_comment("monitor = desc:A##B, preferred"),
            "monitor = desc:A#B, preferred"
        );
        assert_eq!(strip_comment("a ### b"), "a #");
        assert!(parse_line("# monitor = DP-1, disable").is_none());
        assert!(parse_line("monitorv2 = DP-1").is_none());
        assert_eq!(
            parse_line("monitor=desc:A##B,disable").unwrap().selector,
            "desc:A#B"
        );
    }

    #[test]
    fn all_line_forms_parse() {
        let full =
            parse_line("monitor = DP-3, 1920x1080@60, 0x0, 1.5, transform, 3, vrr, 1").unwrap();
        assert_eq!(
            full.form,
            Form::Full {
                mode: "1920x1080@60".into(),
                position: "0x0".into(),
                scale: "1.5".into(),
                transform: 3,
                options: vec![("vrr".into(), "1".into())],
            }
        );
        assert_eq!(
            parse_line("monitor = DP-3, disabled").unwrap().form,
            Form::Disable
        );
        assert_eq!(
            parse_line("monitor = DP-3, transform, 6").unwrap().form,
            Form::Transform(Some(6))
        );
        assert_eq!(
            parse_line("monitor = DP-3, transform, 1.0").unwrap().form,
            Form::Transform(None)
        );
        assert_eq!(
            parse_line("monitor = DP-3, addreserved, 0, 32, 0, 0")
                .unwrap()
                .form,
            Form::AddReserved(vec!["0".into(), "32".into(), "0".into(), "0".into()])
        );
        // Options stop at the first empty key; an empty value is just invalid.
        let Form::Full {
            options, transform, ..
        } = parse_line("monitor = DP-3, preferred, auto, 1, icc, , transform, 1, , vrr, 1")
            .unwrap()
            .form
        else {
            panic!("full line expected");
        };
        assert_eq!(options, vec![("icc".into(), "".into())]);
        assert_eq!(transform, 1);
        for invalid in ["1.0", "abc", "8", "-1", ""] {
            let line = format!("monitor = DP-3, preferred, auto, 1, transform, {invalid}");
            assert!(
                matches!(
                    parse_line(&line).unwrap().form,
                    Form::Full { transform: 0, .. }
                ),
                "{invalid}"
            );
        }
    }

    #[test]
    fn rule_semantics_last_defined_wins_and_selectors_move_to_end() {
        let text = "monitor = DP-3, 1920x1080@60, 0x0, 1, transform, 1\n\
                    monitor = desc:Dell Inc., 1280x1024@75, 100x0, 1\n\
                    monitor = DP-3, transform, 2\n";
        let all = rules(text);
        assert_eq!(
            all.iter().map(|r| r.selector.as_str()).collect::<Vec<_>>(),
            ["desc:Dell Inc.", "DP-3"]
        );
        let dp3 = &live_pair()[1];
        let rule = effective(&all, dp3).unwrap();
        assert_eq!(rule.selector, "DP-3");
        assert_eq!(rule.transform, 2);
        assert_eq!(rule.position, Some((0, 0)));
        // A full line replaces the identical selector with a fresh rule.
        let replaced = rules("monitor = DP-3, preferred, auto, 1, transform, 1\nmonitor = DP-3, preferred, auto, 1\n");
        assert_eq!(replaced.len(), 1);
        assert_eq!(replaced[0].transform, 0);
        // Desc prefixes match and the later rule wins.
        let later = rules("monitor = DP-3, preferred, auto, 1, transform, 1\nmonitor = desc:Dell Inc. DELL, preferred, auto, 1\n");
        assert_eq!(effective(&later, dp3).unwrap().transform, 0);
    }

    #[test]
    fn standalone_transform_and_addreserved_semantics() {
        assert!(rules("monitor = DP-3, transform, 1\n").is_empty());
        let modified = rules("monitor = DP-3, preferred, auto, 1\nmonitor = desc:X, disable\nmonitor = DP-3, transform, 1\n");
        assert_eq!(modified.last().unwrap().selector, "DP-3");
        assert_eq!(modified.last().unwrap().transform, 1);
        let reserved = rules("monitor = DP-3, 1920x1080, 0x0, 1, transform, 3\nmonitor = desc:Y, disable\nmonitor = DP-3, addreserved, 0, 32, 0, 0\n");
        assert_eq!(
            reserved[0].selector, "DP-3",
            "addreserved modifies in place"
        );
        assert_eq!(reserved[0].transform, 3);
        let appended = rules("monitor = DP-3, addreserved, 0, 32, 0, 0\n");
        assert_eq!(appended, vec![Rule::fresh("DP-3")]);
        let disabled =
            rules("monitor = DP-3, preferred, auto, 1, transform, 1\nmonitor = DP-3, disable\n");
        assert!(disabled[0].disabled);
        assert_eq!(disabled[0].transform, 0);
        assert!(effective(&rules("monitor = , preferred, auto, 1\n"), &live_pair()[1]).is_none());
    }

    #[test]
    fn explicit_values_parse_like_hyprland() {
        let rule = &rules("monitor = DP-3, 1920x1080@59.94Hz, -1920x0, 0.1\n")[0];
        assert_eq!(
            rule.mode,
            Some(RuleMode {
                width: 1920,
                height: 1080,
                refresh: Some(59.94)
            })
        );
        assert_eq!(rule.position, Some((-1920, 0)));
        assert_eq!(rule.scale, Some(1.0));
        let auto = &rules("monitor = DP-3, preferred, auto-left, auto\n")[0];
        assert_eq!((auto.mode, auto.position, auto.scale), (None, None, None));
        assert_eq!(
            rules("monitor = DP-3, 1920x1080, 0x0, 1\n")[0]
                .mode
                .unwrap()
                .refresh,
            None
        );
    }

    #[test]
    fn selector_prefers_unique_descriptions_and_falls_back_to_connectors() {
        let live = live_pair();
        assert_eq!(
            choose_selector(&live[1], &live),
            "desc:Dell Inc. DELL P2412H KG49T35D59GU"
        );
        for (first, second) in [
            ("Dell Inc. DELL P2412H", "Dell Inc. DELL P2412H"),
            ("Dell Inc. DELL P2412H", "Dell Inc. DELL P2412H 2"),
            ("Bad # Monitor", "Other"),
            ("Bad, Monitor", "Other"),
            ("", "Other"),
        ] {
            let pair = outputs(&[
                output_json(0, "DP-1", first, (1920, 1080, 60.0), (0, 0), 1.0, 0, &[]),
                output_json(
                    1,
                    "DP-2",
                    second,
                    (1920, 1080, 60.0),
                    (1920, 0),
                    1.0,
                    0,
                    &[],
                ),
            ]);
            assert_eq!(
                choose_selector(&pair[0], &pair),
                "DP-1",
                "{first:?} vs {second:?}"
            );
        }
        let prefixed = outputs(&[
            output_json(
                0,
                "DP-1",
                "Dell Inc. DELL P2412H",
                (1920, 1080, 60.0),
                (0, 0),
                1.0,
                0,
                &[],
            ),
            output_json(
                1,
                "DP-2",
                "Dell Inc. DELL P2412H 2",
                (1920, 1080, 60.0),
                (1920, 0),
                1.0,
                0,
                &[],
            ),
        ]);
        assert_eq!(
            choose_selector(&prefixed[1], &prefixed),
            "desc:Dell Inc. DELL P2412H 2"
        );
    }

    #[test]
    fn writer_migrates_connectors_to_descriptions_with_one_header() {
        let live = live_pair();
        let text = merge(LIVE_FILE, &plan(&live, &live_targets()), &live);
        assert_eq!(
            text,
            format!(
                "{HEADER}\n\nmonitor = desc:Lenovo Group Limited LEN P27h-10 0x01010101, 2560x1440@59.95, 0x0, 1, transform, 0\nmonitor = desc:Dell Inc. DELL P2412H KG49T35D59GU, 1920x1080@60.00, 2560x0, 1, transform, 1\n"
            )
        );
        assert_eq!(
            merge(&text, &plan(&live, &live_targets()), &live),
            text,
            "idempotent"
        );
        assert_eq!(text.matches("# Managed by").count(), 1);
        // The written rules describe exactly the targets.
        let written = rules(&text);
        for (output, target) in live.iter().zip(live_targets()) {
            let rule = effective(&written, output).unwrap();
            assert_eq!(rule.transform, target.transform);
            assert_eq!(rule.position, Some((target.x, target.y)));
            assert_eq!(rule.mode.unwrap().width, target.mode.width);
        }
    }

    #[test]
    fn writer_preserves_unrelated_lines_and_carries_options() {
        let live = live_pair();
        let existing = "# my notes\nmonitor = , preferred, auto, 1\nmonitor = DP-4, 1920x1080@60, 0x0, 1, transform, 1\n\
                        monitor = HEADLESS-2, 1920x1080@60, 9000x0, 1\nmonitor = desc:Old TV, disable\n\
                        source = ~/.config/hypr/extra.conf\n\
                        monitor = DP-3, 1920x1080@60.00, 2560x0, 1.00, transform, 1, vrr, 1, mirror, HDMI-A-1, bitdepth, 10 # dell\n\
                        monitor = DP-3, addreserved, 0, 32, 0, 0\nmonitor = HDMI-A-1, preferred, auto, 1, icc, /icc/a##b.icm\n";
        let targets = vec![
            target("HDMI-A-1", (2560, 1440, 59.95), (0, 0), 1.25, 0),
            target("DP-3", (1920, 1080, 60.0), (2048, 0), 1.0, 1),
        ];
        let text = merge(existing, &plan(&live, &targets), &live);
        let expected = format!(
            "{HEADER}\n\n# my notes\nmonitor = , preferred, auto, 1\nmonitor = DP-4, 1920x1080@60, 0x0, 1, transform, 1\n\
             monitor = HEADLESS-2, 1920x1080@60, 9000x0, 1\nmonitor = desc:Old TV, disable\nsource = ~/.config/hypr/extra.conf\n\n\
             monitor = desc:Lenovo Group Limited LEN P27h-10 0x01010101, 2560x1440@59.95, 0x0, 1.25, transform, 0, icc, /icc/a##b.icm\n\
             monitor = desc:Dell Inc. DELL P2412H KG49T35D59GU, 1920x1080@60.00, 2048x0, 1, transform, 1, vrr, 1, bitdepth, 10\n\
             monitor = desc:Dell Inc. DELL P2412H KG49T35D59GU, addreserved, 0, 32, 0, 0\n"
        );
        assert_eq!(text, expected);
        assert_eq!(
            merge(&text, &plan(&live, &targets), &live),
            text,
            "idempotent"
        );
    }

    #[test]
    fn lines_shared_with_unwritten_outputs_are_kept() {
        let mut live = live_pair();
        let mut other = live[1].clone();
        other.name = "DP-4".into();
        other.description = "Dell Inc. DELL U2415 XYZ".into();
        (other.make, other.model, other.serial) =
            ("Dell Inc.".into(), "DELL U2415".into(), "XYZ".into());
        other.disabled = true;
        live.push(other);
        let existing = "monitor = desc:Dell Inc., disable\nmonitor = DP-3, preferred, auto, 1\n";
        let text = merge(existing, &plan(&live, &live_targets()), &live);
        assert!(text.contains("monitor = desc:Dell Inc., disable\n"));
        assert!(!text.contains("monitor = DP-3, preferred"));
        assert!(text.contains("monitor = desc:Dell Inc. DELL P2412H KG49T35D59GU, 1920x1080@60.00"));
    }

    #[test]
    fn mode_is_written_exactly_as_targeted() {
        let live = live_pair();
        let line = format_line(
            "DP-3",
            &target("DP-3", (1920, 1080, 59.94), (0, 0), 4.0 / 3.0, 5),
            &[],
        );
        assert_eq!(
            line,
            "monitor = DP-3, 1920x1080@59.94, 0x0, 1.333333, transform, 5"
        );
        let text = merge("", &plan(&live, &live_targets()), &live);
        assert!(text.contains("2560x1440@59.95, 0x0, 1, transform, 0"));
    }

    #[test]
    fn replace_is_atomic_backed_up_pruned_and_skips_identical_content() {
        let fixture = Fixture::new();
        let path = ConfPath::for_home(&fixture.0).unwrap();
        assert_eq!(path.read().unwrap(), None);
        assert_eq!(
            replace(&path, None, "first\n", "20261003-120000").unwrap(),
            Written::Replaced
        );
        assert!(fixture.backups().is_empty(), "nothing to back up");
        fs::set_permissions(&path.target, fs::Permissions::from_mode(0o640)).unwrap();
        fs::write(fixture.hypr().join("monitors.conf.bak-scroll"), "manual").unwrap();
        let mut previous = "first\n".to_string();
        for second in 0..7 {
            let next = format!("content {second}\n");
            let stamp = format!("20261003-1200{second:02}");
            replace(&path, Some(&previous), &next, &stamp).unwrap();
            previous = next;
        }
        assert_eq!(fs::read_to_string(&path.target).unwrap(), "content 6\n");
        assert_eq!(
            fs::metadata(&path.target).unwrap().permissions().mode() & 0o777,
            0o640
        );
        let backups = fixture.backups();
        assert_eq!(backups.len(), 6, "{backups:?}");
        assert!(backups.contains(&"monitors.conf.bak-scroll".to_string()));
        assert_eq!(backups[0], "monitors.conf.bak-20261003-120002");
        assert_eq!(
            fs::read_to_string(fixture.hypr().join("monitors.conf.bak-20261003-120006")).unwrap(),
            "content 5\n"
        );
        // Same-second collisions get numbered names that sort after the plain one.
        replace(&path, Some("content 6\n"), "content 7\n", "20261003-120006").unwrap();
        assert!(fixture
            .backups()
            .contains(&"monitors.conf.bak-20261003-120006-2".to_string()));
        let before = fixture.backups();
        assert_eq!(
            replace(&path, Some("content 7\n"), "content 7\n", "20261003-130000").unwrap(),
            Written::Unchanged
        );
        assert_eq!(fixture.backups(), before);
        assert!(replace(&path, Some("stale\n"), "content 8\n", "20261003-140000").is_err());
        assert_eq!(fs::read_to_string(&path.target).unwrap(), "content 7\n");
        let leftovers = fs::read_dir(fixture.hypr())
            .unwrap()
            .flatten()
            .filter(|e| e.file_name().to_string_lossy().ends_with(".tmp"))
            .count();
        assert_eq!(leftovers, 0);
    }

    #[test]
    fn the_new_backup_survives_pruning_when_the_clock_went_back() {
        let fixture = Fixture::new();
        let path = ConfPath::for_home(&fixture.0).unwrap();
        let mut previous = "first\n".to_string();
        replace(&path, None, &previous, "20261003-120000").unwrap();
        for second in 0..6 {
            let next = format!("content {second}\n");
            replace(
                &path,
                Some(&previous),
                &next,
                &format!("20261003-1200{second:02}"),
            )
            .unwrap();
            previous = next;
        }
        replace(
            &path,
            Some(&previous),
            "after clock change\n",
            "20261003-080000",
        )
        .unwrap();
        let backups = fixture.backups();
        assert_eq!(backups.len(), 5, "{backups:?}");
        assert_eq!(
            fs::read_to_string(fixture.hypr().join("monitors.conf.bak-20261003-080000")).unwrap(),
            "content 5\n"
        );
    }

    #[test]
    fn symlinked_conf_replaces_the_target_and_keeps_the_link() {
        let fixture = Fixture::new();
        let dotfiles = fixture.0.join("dotfiles");
        fs::create_dir_all(&dotfiles).unwrap();
        let real = dotfiles.join("monitors.conf");
        fs::write(&real, "old\n").unwrap();
        let link = fixture.hypr().join("monitors.conf");
        symlink(&real, &link).unwrap();
        let path = ConfPath::for_home(&fixture.0).unwrap();
        assert_eq!(path.target, fs::canonicalize(&real).unwrap());
        replace(&path, Some("old\n"), "new\n", "20261003-120000").unwrap();
        assert!(fs::symlink_metadata(&link)
            .unwrap()
            .file_type()
            .is_symlink());
        assert_eq!(fs::read_to_string(&real).unwrap(), "new\n");
        assert_eq!(fixture.backups(), ["monitors.conf.bak-20261003-120000"]);
        fs::remove_file(&real).unwrap();
        assert!(ConfPath::for_home(&fixture.0).is_err(), "dangling link");
    }

    #[test]
    fn backup_names_sort_by_time_then_collision_number() {
        assert_eq!(
            backup_key("monitors.conf.bak-20261003-120000"),
            Some(("20261003-120000".into(), 1))
        );
        assert_eq!(
            backup_key("monitors.conf.bak-20261003-120000-10"),
            Some(("20261003-120000".into(), 10))
        );
        for name in [
            "monitors.conf.bak-scroll",
            "monitors.conf.bak-20261003",
            "monitors.conf.bak-20261003-120000-x",
        ] {
            assert_eq!(backup_key(name), None, "{name}");
        }
        let stamp = local_stamp();
        assert!(
            backup_key(&format!("{BACKUP_PREFIX}{stamp}")).is_some(),
            "{stamp}"
        );
    }
}
