// SPDX-License-Identifier: GPL-2.0-or-later
// Configuration: JSON with // and /* */ comments and trailing commas allowed.
#pragma once

#include "hardwaremap.h"

#include <QHash>
#include <QRegularExpression>
#include <QStringList>
#include <QVariantMap>
#include <optional>

namespace cs {

struct Binding {
    enum Kind { None, Keys, Action, Control, Command, Cycle, Request };
    Kind kind = None;
    QList<KeyChord> keys;  // Keys, or Action/Control fallback when Kdenlive does not answer
    QString name;          // action id, control id, cycle mode, request method
    double scale = 1.0;    // Control: multiplier applied to detents
    QVariantMap options;   // Control/Request options; string values "$mode" expand to the current mode value
    QStringList argv;      // Command
    QString label;
    bool isValid() const { return kind != None; }
    QString describe() const;
};

// Event slots: "key1".."key15", "knobN.turn", "knobN.ccw", "knobN.cw", "knobN.press"
using BindingMap = QHash<QString, Binding>;

struct Layer {
    QString name;
    QVariantMap when;  // dotted context path -> value | "/regex/" | "!value" | [alternatives] | bool
    BindingMap bindings;
};

struct Profile {
    QString name;
    QRegularExpression matchClass;
    QRegularExpression matchTitle;
    bool hasMatch = false;   // false: global fallback profile
    bool kdenlive = false;   // talk to Kdenlive's control-surface interface
    bool fallthrough = true; // unbound slots fall back to the global profile
    QList<Layer> layers;     // first matching layer wins, then base bindings
    BindingMap bindings;
    QHash<QString, QStringList> modes;
    bool matches(const QString &cls, const QString &title) const;
};

struct Settings {
    int coalesceMs = 8;        // minimum spacing between continuous-control sends
    int ackTimeoutMs = 60;     // stop waiting for an in-flight ack after this
    int accelWindowMs = 40;    // detents closer than this count as "fast"
    double accelFactor = 1.0;  // multiplier for fast detents (1 = off)
    int keyRateHz = 120;       // cap for key taps generated by knobs
};

struct DeviceMatch {
    QString vendor = QStringLiteral("1189");
    QString product = QStringLiteral("8890");
    QString serial;
};

struct Config {
    DeviceMatch device;
    HardwareMap hardware = HardwareMap::fromScheme(ch552::Numbering::KeysThenKnobs);
    QString hardwareSource = QStringLiteral("default:keys-then-knobs");
    Settings settings;
    QList<Profile> profiles;

    const Profile *profileFor(const QString &cls, const QString &title) const;
    const Profile *globalProfile() const;
};

QByteArray stripJsonComments(const QByteArray &in);
std::optional<Binding> parseBinding(const QJsonValue &v, QString *error);
std::optional<Config> parseConfig(const QByteArray &jsonc, const QString &baseDir, QString *error);
std::optional<Config> loadConfig(const QString &path, QString *error);
QString expandHome(const QString &path);
QString defaultConfigPath();
QString defaultHardwareMapPath();

// Dotted-path condition matching used for Kdenlive context layers.
bool conditionMatches(const QVariantMap &when, const QVariantMap &context);
QVariant valueAtPath(const QVariantMap &map, const QString &dottedPath);

} // namespace cs
