// SPDX-License-Identifier: GPL-2.0-or-later
// Configuration: JSON with // and /* */ comments and trailing commas allowed.
#pragma once

#include "boardprofile.h"
#include "hardwaremap.h"

#include <QHash>
#include <QJsonObject>
#include <QRegularExpression>
#include <QStringList>
#include <QVariantMap>
#include <optional>

namespace cs {

struct Binding {
    enum Kind { None, Keys, Action, Control, Command, Cycle, Request, Mouse };
    Kind kind = None;
    QList<KeyChord> keys;  // Keys, or Action/Control fallback when Kdenlive does not answer
    QString name;          // action id, control id, cycle mode, request method, mouse action
    double scale = 1.0;    // Control: multiplier applied to detents
    double accel = 0;      // Control: acceleration factor for fast detents; 0 = settings.accelFactor
    QVariantMap options;   // Control/Request options; "$mode" expands to a mode value, "$ctx:path" to a context value
    QString targetFrom;    // context path of the target handle (default per control; e.g. "hoveredColorWheel.target")
    QStringList argv;      // Command
    QString label;
    bool isValid() const { return kind != None; }
    QString describe() const;
};

// Event slots: "key1".."key16", "knobN.turn", "knobN.ccw", "knobN.cw", "knobN.press",
// and "knobN.shift.turn|ccw|cw" (turning while the knob is held down).
using BindingMap = QHash<QString, Binding>;

struct Layer {
    QString name;
    QVariantMap when;  // dotted context path -> value | "/regex/" | "!value" | [alternatives] | bool
    BindingMap bindings;
};

struct Profile {
    QString name;
    QRegularExpression matchClass;
    QRegularExpression matchTitle;
    bool hasMatch = false;   // false: global fallback profile
    bool kdenlive = false;   // talk to Kdenlive's control-surface interface
    bool fallthrough = true; // unbound slots fall back to the global profile
    // Kdenlive only: type the configured stock shortcuts when its control
    // interface is absent (it is off by default). Off: API only, the pad then
    // does nothing in Kdenlive and a notice explains how to enable the interface.
    bool keyFallback = false;
    QList<Layer> layers;     // first matching layer wins, then base bindings
    BindingMap bindings;
    QHash<QString, QStringList> modes;
    bool matches(const QString &cls, const QString &title) const;
};

struct Settings {
    int coalesceMs = 8;        // minimum spacing between continuous-control sends
    int ackTimeoutMs = 60;     // stop waiting for an in-flight ack after this
    int accelWindowMs = 40;    // detents closer than this count as "fast"
    double accelFactor = 1.0;  // multiplier for fast detents (1 = off)
    int keyRateHz = 120;       // cap for key taps generated by knobs
    int gestureIdleMs = 500;   // end an editing gesture after this idle time (host ends at 600)
};

// The daemon only ever grabs this device; vendor/product are not configurable.
constexpr quint16 kPadVendor = 0x1189;
constexpr quint16 kPadProduct = 0x8890;

struct DeviceMatch {
    QString vendor = QStringLiteral("1189");
    QString product = QStringLiteral("8890");
    QString serial;  // empty: any 1189:8890 pad (the first one found)
    // auto: raw events (report 5) when the control-surface firmware answers,
    // else evdev chords; evdev: chords only; raw: prefer raw, evdev if it fails.
    QString input = QStringLiteral("auto");
};

struct Config {
    DeviceMatch device;
    HardwareMap hardware = HardwareMap::fromScheme(ch552::Numbering::KeysThenKnobs);
    QString hardwareSource = QStringLiteral("default:keys-then-knobs");
    // "layout": a board profile id or {"keys": 1..16, "knobs": 0..3, "columns": n}.
    std::optional<BoardProfile> layout;
    Settings settings;
    QList<Profile> profiles;
    QStringList warnings;  // non-fatal findings of the config check

    const Profile *profileFor(const QString &cls, const QString &title) const;
    const Profile *globalProfile() const;
};

// The controls (key1.., knob1..) the hardware map names.
QStringList hardwareControls(const Config &cfg);
// The layout in effect: the firmware's board (when the descriptors name one),
// else the config's "layout", else what the hardware map names. Source:
// firmware | config | hardware-map.
BoardProfile effectiveLayout(const Config &cfg, const QString &firmwareBoard = {});

QByteArray stripJsonComments(const QByteArray &in);
std::optional<Binding> parseBinding(const QJsonValue &v, QString *error);
std::optional<Config> parseConfig(const QByteArray &jsonc, const QString &baseDir, QString *error);
std::optional<Config> loadConfig(const QString &path, QString *error);
// Semantic checks run by parseConfig: errors fail, warnings go to cfg.warnings.
bool checkConfig(Config &cfg, QString *error);
QString expandHome(const QString &path);
QString defaultConfigPath();
QString defaultHardwareMapPath();

// A config error or warning split into what an editor can point at.
struct ConfigIssue {
    QString message;  // the full text
    QString profile, layer, slot;  // empty when the text does not name one
    QJsonObject toJson() const;   // {message, profile, layer, slot}; missing parts are null
};
ConfigIssue describeConfigIssue(const QString &text);

// Dotted-path condition matching used for Kdenlive context layers.
bool conditionMatches(const QVariantMap &when, const QVariantMap &context);
QVariant valueAtPath(const QVariantMap &map, const QString &dottedPath);

} // namespace cs
