//! Generated by smplOS src/shared/keypads/gen.py from registry.json: do not edit.
//! Supported keypads (a working backend), their bootloaders and the scope text.

pub const SUPPORTED_IDS: &[(&str, &str)] = &[("1189", "8890")];
pub const BOOTLOADER_IDS: &[(&str, &str)] = &[("4348", "55e0"), ("1a86", "55e0")];
pub const SCOPE: &str = "Supports CH552 macro keypads (USB ID 1189:8890): the inexpensive \"MINI KeyBoard\"-style pads with 3 to 16 keys and up to 3 knobs. Planned, not working yet: Elgato Stream Deck.";
pub const SCOPE_HELP: &str = "Is yours one? Plug it in: a supported keypad shows up as connected just below. In a terminal, keypad-ctl present (or lsusb) finds USB ID 1189:8890. Other keypads won't show up here.";
